issues_table_MCLA<-function(df,var,rownum,type){
  if(!exists(issues_table)){
    issues_table<-0
    issues_table$rownum<-0
    issues_table$value<-0
    issues_table$type<-0
    issues_table$mean_of_var<-0
    issues_table$median_of_var<-0
    issues_table$locate<-0
    issues_table$enum<-0
    issues_table$date<-0
    issues_table$uuid<-0
    issues_table<-data.frame(issues_table)
    
  }else{
    rownum<-rownum
    value<-df[rownum,'var']
    type<-type
    mean_of_var<-mean(df$var)
    median_of_var<-median(df$var)
    locate<-df[rownum,'A5_Metadata']
    enum<-df[rownum,'A6_Metadata']
    date<-df[rownum,'A7_Metadata']
    uuid<-df[rownum,'_uuid']
    
    list_x<-c("0",rownum,value,type,mean_of_var,median_of_var,locate,enum,date,uuid)
    rbind(issues_table,list_x)
  }
}
